PROGRAM COMPLEXROOT
IMPLICIT NONE
COMPLEX*8::X,XCON,Y,YCON,XSQRT,XCONSQRT,YSQRT,YCONSQRT
X=(4,0.0001);XCON=(4,-0.0001);Y=(-4,0.0001);YCON=(-4,-0.0001)
XSQRT=SQRT(X);XCONSQRT=SQRT(XCON);YSQRT=SQRT(Y);YCONSQRT=SQRT(YCON)
PRINT *,X,XSQRT
PRINT *,XCON,XCONSQRT
PRINT *,Y,YSQRT
PRINT *,YCON,YCONSQRT
END PROGRAM
